		//AUTOGENERATED FUNCTION. Check the script in https://github.com/vLabayen/html2js
		//The output should be a element such that contains the following structure:
		//<tr>
		//  <td style="text-align: center"> FECHA </td>
		//  <td style="text-align: center"> CLIENTE </td>
		//  <td style="text-align: center"> USER </td>
		//  <td style="text-align: center"> SERVER </td>
		//  <td style="text-align: center"> NAT </td>
		//  <td style="text-align: center"> DESTINO </td>
		//  <td style="text-align: center"> DURACION </td>
		//  <td style="text-align: center"> START </td>
		//  <td style="text-align: center"> END </td>
		//</tr>
		function table_row(fecha, cliente, user, server, nat, destino, duracion, start, end) {
			let tr_1 = document.createElement('tr');

			let td_1 = document.createElement('td');
			td_1.style = "text-align: center";

			let td_2 = document.createElement('td');
			td_2.style = "text-align: center";

			let td_3 = document.createElement('td');
			td_3.style = "text-align: center";

			let td_4 = document.createElement('td');
			td_4.style = "text-align: center";

			let td_5 = document.createElement('td');
			td_5.style = "text-align: center";

			let td_6 = document.createElement('td');
			td_6.style = "text-align: center";

			let td_7 = document.createElement('td');
			td_7.style = "text-align: center";

			let td_8 = document.createElement('td');
			td_8.style = "text-align: center";

			let td_9 = document.createElement('td');
			td_9.style = "text-align: center";

			td_1.appendChild(document.createTextNode(' FECHA '));
			tr_1.appendChild(td_1);
			td_2.appendChild(document.createTextNode(' CLIENTE '));
			tr_1.appendChild(td_2);
			td_3.appendChild(document.createTextNode(' USER '));
			tr_1.appendChild(td_3);
			td_4.appendChild(document.createTextNode(' SERVER '));
			tr_1.appendChild(td_4);
			td_5.appendChild(document.createTextNode(' NAT '));
			tr_1.appendChild(td_5);
			td_6.appendChild(document.createTextNode(' DESTINO '));
			tr_1.appendChild(td_6);
			td_7.appendChild(document.createTextNode(' DURACION '));
			tr_1.appendChild(td_7);
			td_8.appendChild(document.createTextNode(' START '));
			tr_1.appendChild(td_8);
			td_9.appendChild(document.createTextNode(' END '));
			tr_1.appendChild(td_9);
			return tr_1;
		}
