		//AUTOGENERATED FUNCTION. Check the script in https://github.com/vLabayen/html2js
		//The output should be a element such that contains the following structure:
		//<table id="tablaRaw" class="table table-striped" style="color:white; width: 100%">
		//  <thead>
		//    <tr style="background-color: MidnightBlue;">
		//      <th scope="col" style="text-align: center"> Fecha - Hora </th>
		//      <th scope="col" style="text-align: center"> IP Cliente </th>
		//      <th scope="col" style="text-align: center"> Usuario </th>
		//      <th scope="col" style="text-align: center"> VServer </th>
		//      <th scope="col" style="text-align: center"> IP NAT </th>
		//      <th scope="col" style="text-align: center"> Destino </th>
		//      <th scope="col" style="text-align: center"> Duración </th>
		//      <th scope="col" style="text-align: center"> Inicio </th>
		//      <th scope="col" style="text-align: center"> Final </th>
		//    </tr>
		//  </thead>
		//  <tbody id="tableBody"> </tbody>
		//</table>
		function table_header() {
			let tablaRaw = document.createElement('table');
			tablaRaw.id = "tablaRaw";
			tablaRaw.classList.add(...['table', 'table-striped']);
			tablaRaw.style = "color:white; width: 100%";

			let thead_1 = document.createElement('thead');

			let tr_1 = document.createElement('tr');
			tr_1.style = "background-color: MidnightBlue;";

			let th_1 = document.createElement('th');
			th_1.setAttribute("scope", "col");
			th_1.style = "text-align: center";

			let th_2 = document.createElement('th');
			th_2.setAttribute("scope", "col");
			th_2.style = "text-align: center";

			let th_3 = document.createElement('th');
			th_3.setAttribute("scope", "col");
			th_3.style = "text-align: center";

			let th_4 = document.createElement('th');
			th_4.setAttribute("scope", "col");
			th_4.style = "text-align: center";

			let th_5 = document.createElement('th');
			th_5.setAttribute("scope", "col");
			th_5.style = "text-align: center";

			let th_6 = document.createElement('th');
			th_6.setAttribute("scope", "col");
			th_6.style = "text-align: center";

			let th_7 = document.createElement('th');
			th_7.setAttribute("scope", "col");
			th_7.style = "text-align: center";

			let th_8 = document.createElement('th');
			th_8.setAttribute("scope", "col");
			th_8.style = "text-align: center";

			let th_9 = document.createElement('th');
			th_9.setAttribute("scope", "col");
			th_9.style = "text-align: center";

			let tableBody = document.createElement('tbody');
			tableBody.id = "tableBody";

			th_1.appendChild(document.createTextNode(' Fecha - Hora '));
			tr_1.appendChild(th_1);
			th_2.appendChild(document.createTextNode(' IP Cliente '));
			tr_1.appendChild(th_2);
			th_3.appendChild(document.createTextNode(' Usuario '));
			tr_1.appendChild(th_3);
			th_4.appendChild(document.createTextNode(' VServer '));
			tr_1.appendChild(th_4);
			th_5.appendChild(document.createTextNode(' IP NAT '));
			tr_1.appendChild(th_5);
			th_6.appendChild(document.createTextNode(' Destino '));
			tr_1.appendChild(th_6);
			th_7.appendChild(document.createTextNode(' Duración '));
			tr_1.appendChild(th_7);
			th_8.appendChild(document.createTextNode(' Inicio '));
			tr_1.appendChild(th_8);
			th_9.appendChild(document.createTextNode(' Final '));
			tr_1.appendChild(th_9);
			thead_1.appendChild(tr_1);
			tablaRaw.appendChild(thead_1);
			tablaRaw.appendChild(tableBody);
			return tablaRaw;
		}
